<a href="https://colab.research.google.com/github/HarshiniAiyyer/Relearning/blob/main/pytorch/PyTorch_Detailed_Tutorial_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. Pytorch Fundamentals

In [31]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors


### Creating Tensors

- Building blocks of DL
- Tensors are created using ```torch.Tensor()```

In [32]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

#### Scalar

- No dimensions

In [33]:
scalar.ndim

0

In [34]:
#get tensor back as python int

scalar.item()

7

#### Vector
- it has magnitude and direction

In [35]:
#Vector

vec = torch.tensor([7,7])
vec

tensor([7, 7])

In [36]:
vec.shape


torch.Size([2])

#### Matrix

In [37]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [38]:
MATRIX[0]

tensor([7, 8])

#### Tensor

In [39]:
tens = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
tens

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [40]:
tens.shape

torch.Size([1, 3, 3])

We got a single 3x3 shaped tensor.

#### Random Tensors

- NN start with tensors full of random numbers and then adjust those random numbers to represent the data. They are the weights for the NN.

`Start with random numbers -> look at data -. update weights -> look at data -> update`

In [41]:
rat = torch.rand(3,4)
rat

tensor([[0.7160, 0.0314, 0.6057, 0.7997],
        [0.3441, 0.2858, 0.4805, 0.3113],
        [0.3974, 0.1434, 0.8264, 0.7110]])

In [42]:
rat.ndim

2

3 x 4 = 12 elements

#### Image Tensors

In [43]:
imgten = torch.rand(size = (224,224,3)) #h, w, color channels - ideally RGB
imgten

tensor([[[0.3958, 0.4239, 0.9483],
         [0.9552, 0.8359, 0.2632],
         [0.5259, 0.7630, 0.9526],
         ...,
         [0.3496, 0.5022, 0.3420],
         [0.9548, 0.8725, 0.4017],
         [0.7660, 0.6766, 0.0631]],

        [[0.3865, 0.3377, 0.0249],
         [0.2975, 0.8266, 0.7850],
         [0.6587, 0.0294, 0.9341],
         ...,
         [0.9596, 0.2780, 0.4888],
         [0.6253, 0.4782, 0.3129],
         [0.9055, 0.2404, 0.3144]],

        [[0.9813, 0.0928, 0.2328],
         [0.0140, 0.9965, 0.2649],
         [0.1811, 0.2783, 0.5259],
         ...,
         [0.5144, 0.9916, 0.4518],
         [0.5300, 0.1730, 0.0188],
         [0.9820, 0.1964, 0.3794]],

        ...,

        [[0.3073, 0.9785, 0.2645],
         [0.4333, 0.1780, 0.9346],
         [0.8962, 0.8525, 0.3200],
         ...,
         [0.2525, 0.1778, 0.5234],
         [0.1079, 0.0388, 0.9392],
         [0.9419, 0.5106, 0.2433]],

        [[0.8340, 0.9553, 0.2426],
         [0.8472, 0.5492, 0.3212],
         [0.

In [44]:
torch.rand(size = (3,3))

tensor([[0.5769, 0.5420, 0.6708],
        [0.8955, 0.6000, 0.8260],
        [0.7838, 0.7962, 0.9440]])

#### Zeros and Ones Tensor

- Useful for creating masks for NNs.

In [45]:
ze = torch.zeros(size = (3,4))
ze

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [46]:
one = torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

IMP -> Default dtype is float32.

#### Arange and Zeros-Like

##### Creating range of tensors and tensors-like

- `range` is deprecated. Use `arange` instead.

- Define a tensor similar to another

In [47]:
#torch.arange

er = torch.arange(start = 0, end = 10, step = 2)
er

tensor([0, 2, 4, 6, 8])

In [48]:
#tensors-like
ert = torch.zeros_like(er)
ert

tensor([0, 0, 0, 0, 0])

### Tensor DataTypes

In [49]:
f32tensor = torch.tensor([3.0,6.0,9.0],
                         dtype = None,
                         device = None, #what device is ur tensor on?
                         requires_grad= False) #tracks gradients

f32tensor

tensor([3., 6., 9.])

**Note: **

If tensors are =>

- Not the right datatype: get datatype by using `tensor.dtype`

- Not right shape, use `tensor.shape`

- Not on the right device, use `tensor.device`


In [50]:
print(f"Datatype : {rat.dtype}")
print(f'Shape: {rat.shape}')
print(f"Device is on: {rat.device}")

Datatype : torch.float32
Shape: torch.Size([3, 4])
Device is on: cpu


### Manipulating Tensors

- Addition
- Subtraction
- Element Wise Multiplication
- Division
- Matrix Multiplication

In [51]:
print(torch.matmul(torch.rand(3,2), torch.rand(2,3)).ndim)

2


## Tensor Aggregation (min, max, sum, etc)

In [52]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
x.max()

tensor(90)

In [54]:
x = torch.tensor([10, 5, 20, 8])

# Functional form
max_value_func = torch.max(x)
print(f"Using torch.max(x): {max_value_func}")

# Method form
max_value_method = x.max()
print(f"Using x.max(): {max_value_method}")

Using torch.max(x): 20
Using x.max(): 20


In [55]:
#mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(10.7500), tensor(10.7500))

#### Argmin(), Argmax(): Find positional min and max of tensors

In [56]:
#find the position with minimum and maximum value.
#Returns index
x.argmin(), x.argmax()

(tensor(1), tensor(2))

## Reshaping, stacking, Squeezing and unsqueezing tensors

- reshaping : fixing shapes / dimensions
- view -> return a view of the input tnesor but the same memory as the original tensor
- stacking -> multi tensors on top of the other (vstack) or side by side (hstack)

- squeeze -> removes all 1D from a tensor
- unsqueeze -> add 1D to a target tensor

- permute -> return a view of the input with dimensions permuted (swapped) in a certain way


In [57]:
import torch

x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

##### Reshape

In [58]:
#add an extra dimension

xr = x.reshape(1,9)
xr, xr.shape, xr.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

##### View

In [59]:
z = x.view(1,9)
z.shape

torch.Size([1, 9])

In [60]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

##### Stacking

- hstack uses dim = 0,
- vstack uses dim = 1

In [61]:
xs = torch.stack([x,x,x,x], dim = 1)
xs

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

##### Permute

- Used widely with images

In [62]:
y = torch.rand(2,3,4)
y.size()

torch.Size([2, 3, 4])

In [63]:
torch.permute(y,(2,0,1)).size()

torch.Size([4, 2, 3])

In [64]:
xorig = torch.rand(size = (224, 224, 3))

xperm = xorig.permute(2,0,1)  #swaps the position of the axis

print(f"Previous shape: {xorig.shape}")
print(f"New shape: {xperm.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from Tensors)

Indexing with Pytorch is similar to indexing with Numpy.

In [65]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [66]:
#index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [67]:
#lets index on the most inner bracket (last dim)
x[0][1][1]

tensor(5)

In [68]:
# : can also be used to select either row or col
x[:,0]

tensor([[1, 2, 3]])

In [69]:
#get all values of 0th and 1st dim but only index 1 of 2nd dimension

x[:,:,1]

tensor([[2, 5, 8]])

In [70]:
#get all values of 0th and 1st dim but only 1 index of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [71]:
#get index 0 of the 0th and 1st dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [72]:
#print 3,6,9

x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch and Numpy

- numpy array to pytorch tensor
```torch.from_numpy(ndarray)```

- pytorch tensor to numpy array ```torch.Tensor.numpy()```

#### Numpy to Tensor

In [74]:
import torch
import numpy as np

arr = np.arange(1.0,8.0)
tens = torch.from_numpy(arr)
arr, tens

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Note:
- dtype of numpy is float64
- dtype of tensor is float32

#### Tensor to numpy

In [76]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [77]:
#change tensor to array, what happends to numpytensor?

tensor = tensor  + 1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

Shared memory hence the array changes

## Random Seed - Reproducibility in Pytorch

How a NN learns

- start with random nos -> then tensor operations -> update random nos to try and make them better representations of the data
-> and so on

- To reduce randommness in NN, and Pytorch, comes the concept of a ``random seed``

- Essentially what the random seed does is the 'flavor' the randomness. Or pseudo-randomness or generative randomness

In [80]:
import torch

randtensA = torch.rand(3,4)
randtensB = torch.rand(3,4)

randtensA, randtensB

(tensor([[0.8549, 0.8174, 0.9249, 0.6742],
         [0.5581, 0.8776, 0.1531, 0.7265],
         [0.8948, 0.2010, 0.5806, 0.0456]]),
 tensor([[0.0164, 0.7499, 0.8925, 0.0137],
         [0.3633, 0.2373, 0.1406, 0.0802],
         [0.2355, 0.2159, 0.9855, 0.1532]]))

In [81]:
print(randtensA == randtensB)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


#### Random but reproducible tensors

In [83]:
import torch

random_seed = 42  #we have different flavors - 42, 75 etc..

torch.manual_seed(random_seed)
randtensC = torch.rand(3,4)

#use manual seed everytime because it doesnt work for all together
torch.manual_seed(random_seed)
randtensD = torch.rand(3,4)

print(randtensC, randtensD)
print(randtensC == randtensD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on GPUs

- GPUs = faster computations

#### Check nvidia configuration

In [84]:
!nvidia-smi

Sat Nov  1 20:10:00 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   44C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

#### Check for GPU access with Pytorch

In [85]:
import torch
torch.cuda.is_available()

True

#### Set up device agnostic code

In [86]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

#### Count GPUs

In [87]:
torch.cuda.device_count()

1

## Putting tensors and models on the GPUs

- adding them to GPUs because using a GPU results in faster computations

In [88]:
tens = torch.tensor([1,2,3])

print(tens, tens.device) #check if its on the cpu

tensor([1, 2, 3]) cpu


#### Move tensor to gpu

In [89]:
#move tensor to gpu

tensorgpu = tensor.to(device)
tensorgpu

tensor([2., 2., 2., 2., 2., 2., 2.], device='cuda:0')

- Numpy works better on the CPU.

- If tensor is on GPU, cant transform it to Numpy

- first set the tensor to the cpu, then convert it to Numpy

In [90]:
tensorback = tensorgpu.cpu().numpy()
tensorback

array([2., 2., 2., 2., 2., 2., 2.], dtype=float32)

This concludes the end of the PyTorch Fundamentals notebook.